version: "3"

services:
    db:
        image: mongo:3.4
        build:
            context: ./
            dockerfile: Dockerfile-mongo
        volumes:
            - ${LOCAL_DATA_DIR}:/data
        entrypoint: mongod --config /etc/mongodb-conf.yaml
    web:
        image: node:boron
        build:
            context: ./web 
            dockerfile: Dockerfile-web
        entrypoint: ./entrypoint.sh 
        volumes:
            - ./web/src:/web/web/src