version: "3"

services:
    db:
        image: mongo:3.4
        build:
            context: ./
            dockerfile: Dockerfile-mongo
        volumes:
            - ${LOCAL_DATA_DIR}:/data
        entrypoint: mongod --config /etc/mongodb-conf.yaml

    web:
        build:
            context: . 
            dockerfile: web/Dockerfile
        entrypoint: /web/entrypoint.sh 
        volumes:
            - ./web/src:/web/src
