version: "3"

services:
    db:
        image: mongo:3.4
        build:
            context: ./
            dockerfile: Dockerfile-mongo
        volumes:
            - ${LOCAL_DATA_DIR}:/data
        entrypoint: mongod --config /etc/mongodb-conf.yaml \
                    --port 27027 --bind_ip 0.0.0.0 --auth
        ports:
            - 27027:27027

    web:
        build:
            context: . 
            dockerfile: web/Dockerfile
        entrypoint: /web/entrypoint.sh 
        volumes:
            - ./web/src:/web/src
    api:
        build:
            context: .
            dockerfile: api/Dockerfile
        entrypoint: /api/entrypoint.sh
        volumes:
            - ./api/src:/api/src
        ports:
            - 3000:3000

    he_twitter_miner:
        build: .\he_twitter_miner
        volumes:
        - ./he_twitter_miner/src:/usr/src/app
        - ./config:/usr/src/app/config
#        restart: on-failure
