services:
  backup:
    build:
      context: .
      dockerfile: Dockerfile
    volume:
      - ../../config:/scripts/backup
      - ${LOCAL_DATA_DIR}:/data
      - /var/log:/scripts/log
    entrypoint: python backup_database.py ${LOCAL_DATA_DIR} /scripts/backup/config.yaml